version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DOCKER_API_VERSION='1.41'
    labels:
      - "webhook.enable=true"
    volumes:
      - ./docker-compose-test:/compose
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/app